apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: p7-kafka-vol1
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 50Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: p7-kafka-vol2
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 50Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: p7-kafka-vol3
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 50Gi
