apiVersion: v1
kind: Service
metadata:
  name: p7-kafka-zk
spec:
  ports:
  - name: 2181-tcp
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: 2888-tcp
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: 3888-tcp
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    app: p7-kafka-zk
  sessionAffinity: None
  type: ClusterIP
