apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: zookeeper-localstore-deploy
    hawkular-openshift-agent-example: jolokia-wildfly
    name: hawkular-openshift-agent-zookeeper
  name: hawkular-openshift-agent-zookeeper-1
  namespace: common-infrastructure
data:
  hawkular-openshift-agent: |
    endpoints:
    - type: jolokia
      protocol: http
      port: 8778
      path: /jolokia/
      collection_interval: 15s
      metrics:
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1#QuorumSize
        type: gauge
        description: "QuorumSize"
        tags:
          descriptor_name: QuorumSize
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#MaxSessionTimeout
        type: gauge
        description: "MaxSessionTimeout"
        tags:
          descriptor_name: MaxSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#MinSessionTimeout
        type: gauge
        description: "MinSessionTimeout"
        tags:
          descriptor_name: MinSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#TickTime
        type: gauge
        description: "TickTime"
        tags:
          descriptor_name: TickTime
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#Tick
        type: gauge
        description: "Tick"
        tags:
          descriptor_name: Tick
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#ElectionType
        type: gauge
        description: "ElectionType"
        tags:
          descriptor_name: ElectionType
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#SyncLimit
        type: gauge
        description: "SyncLimit"
        tags:
          descriptor_name: SyncLimit
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#InitLimit
        type: gauge
        description: "InitLimit"
        tags:
          descriptor_name: InitLimit
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1#MaxClientCnxnsPerHost
        type: gauge
        description: "MaxClientCnxnsPerHost"
        tags:
          descriptor_name: MaxClientCnxnsPerHost
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#PacketsReceived
        type: counter
        description: "PacketsReceived"
        tags:
          descriptor_name: PacketsReceived
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#PacketsSent
        type: counter
        description: "PacketsSent"
        tags:
          descriptor_name: PacketsSent
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#MinSessionTimeout
        type: gauge
        description: "MinSessionTimeout"
        tags:
          descriptor_name: MinSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#MaxSessionTimeout
        type: gauge
        description: "MaxSessionTimeout"
        tags:
          descriptor_name: MaxSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#MinRequestLatency
        type: gauge
        description: "MinRequestLatency"
        tags:
          descriptor_name: MinRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#AvgRequestLatency
        type: gauge
        description: "AvgRequestLatency"
        tags:
          descriptor_name: AvgRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#MaxRequestLatency
        type: gauge
        description: "MaxRequestLatency"
        tags:
          descriptor_name: MaxRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#NumAliveConnections
        type: gauge
        description: "NumAliveConnections"
        tags:
          descriptor_name: NumAliveConnections
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#TickTime
        type: gauge
        description: "TickTime"
        tags:
          descriptor_name: TickTime
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#OutstandingRequests
        type: gauge
        description: "OutstandingRequests"
        tags:
          descriptor_name: OutstandingRequestss
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader#MaxClientCnxnsPerHost
        type: gauge
        description: "MaxClientCnxnsPerHost"
        tags:
          descriptor_name: MaxClientCnxnsPerHost
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader,name3=InMemoryDataTree#WatchCount
        type: gauge
        description: "WatchCount"
        tags:
          descriptor_name: WatchCount
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Leader,name3=InMemoryDataTree#NodeCount
        type: gauge
        description: "NodeCount"
        tags:
          descriptor_name: NodeCount
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#PacketsReceived
        type: counter
        description: "PacketsReceived"
        tags:
          descriptor_name: PacketsReceived
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#PacketsSent
        type: counter
        description: "PacketsSent"
        tags:
          descriptor_name: PacketsSent
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#MinSessionTimeout
        type: gauge
        description: "MinSessionTimeout"
        tags:
          descriptor_name: MinSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#MaxSessionTimeout
        type: gauge
        description: "MaxSessionTimeout"
        tags:
          descriptor_name: MaxSessionTimeout
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#MinRequestLatency
        type: gauge
        description: "MinRequestLatency"
        tags:
          descriptor_name: MinRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#AvgRequestLatency
        type: gauge
        description: "AvgRequestLatency"
        tags:
          descriptor_name: AvgRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#MaxRequestLatency
        type: gauge
        description: "MaxRequestLatency"
        tags:
          descriptor_name: MaxRequestLatency
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#NumAliveConnections
        type: gauge
        description: "NumAliveConnections"
        tags:
          descriptor_name: NumAliveConnections
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#TickTime
        type: gauge
        description: "TickTime"
        tags:
          descriptor_name: TickTime
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#OutstandingRequests
        type: gauge
        description: "OutstandingRequests"
        tags:
          descriptor_name: OutstandingRequestss
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#PendingRevalidationCount
        type: gauge
        description: "PendingRevalidationCount"
        tags:
          descriptor_name: PendingRevalidationCount
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower#MaxClientCnxnsPerHost
        type: gauge
        description: "MaxClientCnxnsPerHost"
        tags:
          descriptor_name: MaxClientCnxnsPerHost
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower,name3=InMemoryDataTree#WatchCount
        type: gauge
        description: "WatchCount"
        tags:
          descriptor_name: WatchCount
          container_name: ${POD:label[deploymentconfig]}
      - name: org.apache.ZooKeeperService:name0=ReplicatedServer_id1,name1=replica.1,name2=Follower,name3=InMemoryDataTree#NodeCount
        type: gauge
        description: "NodeCount"
        tags:
          descriptor_name: NodeCount
          container_name: ${POD:label[deploymentconfig]}
