apiVersion: v1
kind: Service
metadata:
  name: confluent
  labels:
    app: confluent
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
spec:
  ports:
  - name: 9092-tcp
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: 9093-tcp
    port: 9093
    protocol: TCP
    targetPort: 9093
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deploymentconfig: confluent
  sessionAffinity: None
  type: ClusterIP
