apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Route
  metadata:
    name: p7-kafka-1
    labels:
      app: kafka-deploy
  spec:
    host: kafka-broker-1.app.10.92.2.206.xip.io
    port:
      targetPort: 9093-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: p7-kafka-1
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: p7-kafka-2
    labels:
      app: kafka-deploy
  spec:
    host: kafka-broker-2.app.10.92.2.206.xip.io
    port:
      targetPort: 9093-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: p7-kafka-2
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: p7-kafka-3
    labels:
      app: kafka-deploy
  spec:
    host: kafka-broker-3.app.10.92.2.206.xip.io
    port:
      targetPort: 9093-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: p7-kafka-3
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: p7-kafka-zk
    labels:
      app: zookeeper-deploy
  spec:
    host: kafka-zk.app.10.92.2.206.xip.io
    port:
      targetPort: 2181-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: p7-kafka-zk
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Route
  metadata:
    name: p7-kafka-zk-3
    labels:
      app: zookeeper-deploy
  spec:
    host: kafka-zk-3.app.10.92.2.206.xip.io
    port:
      targetPort: 2181-tcp
    tls:
      termination: passthrough
    to:
      kind: Service
      name: p7-kafka-zk-3
      weight: 100
    wildcardPolicy: None
